using System;
using System.Collections.Generic;
using MVZ2.Cursors;
using MVZ2.GameContent.Armors;
using MVZ2.HeldItems;
using MVZ2.Level;
using MVZ2.Managers;
using MVZ2.Models;
using MVZ2.UI;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Level;
using MVZ2Logic;
using MVZ2Logic.Entities;
using MVZ2Logic.Games;
using MVZ2Logic.HeldItems;
using MVZ2Logic.Level;
using PVZEngine;
using PVZEngine.Armors;
using PVZEngine.Buffs;
using PVZEngine.Entities;
using PVZEngine.Level;
using PVZEngine.Models;
using PVZEngine.Modifiers;
using Tools;
using UnityEngine;
using UnityEngine.EventSystems;

namespace MVZ2.Entities
{
    public class EntityController : MonoBehaviour, ILevelRaycastReceiver, ITooltipTarget
    {
        #region 公有方法
        public void Init(LevelController level, Entity entity)
        {
            Level = level;
            Entity = entity;
            rng = new RandomGenerator(entity.InitSeed);
            isHighlight = false;
            gameObject.name = entity.ToString();
            transform.position = Level.LawnToTrans(Entity.Position);
            lastPosition = transform.position;

            entity.PostInit += PostInitCallback;
            entity.PostPropertyChanged += PostPropertyChangedCallback;
            entity.OnChangeModel += OnChangeModelCallback;
            entity.OnModelInsertionAdded += OnModelInsertionAddedCallback;
            entity.OnModelInsertionRemoved += OnModelInsertionRemovedCallback;

            entity.OnEquipArmor += OnArmorEquipCallback;
            entity.OnRemoveArmor += OnArmorRemoveCallback;


            holdStreakHandler.ResetData();
            RemoveCursorSource();

            entity.SetModelInterface(bodyModelInterface);
            SetModel(Entity.ModelID);
            if (Model)
            {
                ClearAllArmorModels();
                var lvl = Entity.Level;
                var heldItemDef = lvl.GetHeldItemDefinition();
                UpdateModelColliderActive(heldItemDef?.GetHeldTargetMask(lvl) ?? HeldTargetFlag.None);
            }
        }
        public void RemoveEntity()
        {
            Entity.PostInit -= PostInitCallback;
            Entity.PostPropertyChanged -= PostPropertyChangedCallback;
            Entity.OnChangeModel -= OnChangeModelCallback;
            Entity.OnModelInsertionAdded -= OnModelInsertionAddedCallback;
            Entity.OnModelInsertionRemoved -= OnModelInsertionRemovedCallback;

            Entity.OnEquipArmor -= OnArmorEquipCallback;
            Entity.OnRemoveArmor -= OnArmorRemoveCallback;
            Entity.SetModelInterface(null);
        }

        #region 模型
        public void SetModel(NamespaceID modelId)
        {
            if (Model)
            {
                Destroy(Model.gameObject);
                Model.OnUpdateFrame -= OnModelUpdateFrameCallback;
                Model = null;
            }
            var builder = new ModelBuilder(modelId, Level.GetCamera(), Entity.InitSeed);
            var model = builder.Build(transform);
            Model = model as EntityModel;
            if (!Model)
                return;
            Model.OnUpdateFrame += OnModelUpdateFrameCallback;
            modelPropertyCache.UpdateAll(this);
            Model.UpdateFrame(0);
            Model.UpdateAnimators(0);
            UpdateModelInsertions();

            // 重新创建护甲模型
            foreach (var slot in Entity.GetActiveArmorSlots())
            {
                var armor = Entity.GetArmorAtSlot(slot);
                if (armor != null)
                {
                    CreateArmorModel(slot, armor);
                }
            }
        }
        public void SetSimulationSpeed(float simulationSpeed)
        {
            if (Model)
            {
                Model.SetSimulationSpeed(simulationSpeed);
            }
        }
        #endregion

        #region 更新
        public void UpdateFixed()
        {
            if (Model)
            {
                Model.UpdateFixed();
            }
            holdStreakHandler.UpdateHoldAndStreak();
        }
        public void UpdateFrame(float deltaTime)
        {
            var posOffset = GetTransformOffset();

            var pos = Entity.Position;
            var currentTransPos = Level.LawnToTrans(pos);
            transform.position = Vector3.Lerp(lastPosition, currentTransPos + posOffset, 0.5f);
            UpdateShadow();
            UpdateHeightIndicator();
            lastPosition = transform.position;

            var shouldTwinkle = ShouldTwinkle();
            if (twinkling != shouldTwinkle)
            {
                twinkling = shouldTwinkle;
                modelPropertyCache.SetDirtyProperty(EntityPropertyCache.PropertyName.Tint);
            }
            else if (twinkling)
            {
                modelPropertyCache.SetDirtyProperty(EntityPropertyCache.PropertyName.Tint);
            }
            if (Model)
            {
                Model.UpdateFrame(deltaTime);
            }
        }
        public void UpdateAnimators(float deltaTime)
        {
            if (Model)
            {
                Model.UpdateAnimators(deltaTime);
            }
        }
        public void GetAnimatorsToUpdate(IList<Animator> results)
        {
            if (Model)
            {
                Model.GetAnimatorsToUpdate(results);
            }
        }
        #endregion

        public void UpdateModelColliderActive(HeldTargetFlag flag)
        {
            if (Model is EntityModel sprModel)
            {
                var heldTargetFlag = HeldTargetFlagHelper.GetHeldTargetFlagByType(Entity.Type);
                sprModel.SetColliderActive((flag & heldTargetFlag) != HeldTargetFlag.None);
            }
        }
        public void SetHighlight(bool highlight)
        {
            isHighlight = highlight;
            modelPropertyCache.SetDirtyProperty(EntityPropertyCache.PropertyName.ColorOffset);
        }
        public bool IsHovered() => holdStreakHandler.IsHovered();
        public bool IsPressed() => holdStreakHandler.IsPressed();
        public int GetHoveredPointerCount() => holdStreakHandler.GetHoveredPointerCount();
        public PointerEventData GetHoveredPointerEventData(int index) => holdStreakHandler.GetHoveredPointerEventData(index);
        public Vector2 TransformWorld2ColliderPosition(Vector3 worldPosition)
        {
            if (Model is not EntityModel spriteModel)
                return Vector2.zero;
            var collider = spriteModel.Collider;
            if (collider is not BoxCollider2D boxCollider)
                return Vector2.zero;
            var pos2D = (Vector2)(collider.transform.position + collider.transform.TransformDirection(collider.offset));
            var lossyScale = (Vector2)collider.transform.lossyScale;
            var size = boxCollider.size;
            var lossySize = Vector2.Scale(size, lossyScale);
            var origin = pos2D - lossySize * 0.5f;

            var relativeWorldPos = (Vector2)worldPosition - origin;
            var colliderX = relativeWorldPos.x / lossySize.x;
            var colliderY = relativeWorldPos.y / lossySize.y;

            return new Vector2(colliderX, colliderY);
        }
        public HeldItemTargetEntity GetHeldItemTarget(Vector3 worldPosition)
        {
            var pos = TransformWorld2ColliderPosition(worldPosition);
            return new HeldItemTargetEntity(Entity, pos);
        }
        public HeldItemTargetEntity GetHeldItemTarget(PointerEventData data)
        {
            var pos = Vector2.zero;
            if (data != null)
            {
                pos = TransformWorld2ColliderPosition(data.pointerCurrentRaycast.worldPosition);
            }
            return new HeldItemTargetEntity(Entity, pos);
        }
        public SerializableEntityController ToSerializable()
        {
            return new SerializableEntityController()
            {
                id = Entity.ID,
                model = Model ? Model.ToSerializable() : null
            };
        }
        public void LoadFromSerializable(SerializableEntityController serializable)
        {
            if (Model && serializable.model != null)
            {
                Model.LoadFromSerializable(serializable.model);
                UpdateModelInsertions();
            }
        }
        #endregion

        #region 私有方法

        #region 生命周期
        private void Awake()
        {
            holdStreakHandler.OnPointerInteraction += (_, d, i) => OnPointerInteraction?.Invoke(this, d, i);
            bodyModelInterface = new BodyModelInterface(this);
        }
        private void Update()
        {
            var engine = Entity.Level;
            bool cursorValid = IsHovered() && Level.IsGameRunning() && !engine.IsHoldingItem();
            if (cursorValid)
            {
                AddCursorSource();
            }
            else
            {
                RemoveCursorSource();
            }
        }
        #endregion

        #region 事件回调
        private void PostInitCallback()
        {
            UpdateAnimators(0);
            UpdateFrame(0);
        }
        private void PostPropertyChangedCallback(IPropertyKey key, object beforeValue, object afterValue)
        {
            modelPropertyCache.SetDirtyProperty(key);
        }
        private void OnChangeModelCallback(NamespaceID modelID)
        {
            SetModel(modelID);
        }
        private void OnModelInsertionAddedCallback(ModelInsertion insertion)
        {
            if (Model)
                Model.AddModelInsertion(insertion);
        }
        private void OnModelInsertionRemovedCallback(ModelInsertion insertion)
        {
            if (Model)
                Model.RemoveModelInsertion(insertion.key);
        }
        private void OnArmorEquipCallback(NamespaceID slot, Armor armor)
        {
            CreateArmorModel(slot, armor);
        }
        private void OnArmorRemoveCallback(NamespaceID slot, Armor armor)
        {
            RemoveArmorModel(slot);
        }
        private void OnModelUpdateFrameCallback(float deltaTime)
        {
            UpdateArmorModels();
            UpdateEntityModel();
        }
        #endregion

        #region 接口实现
        bool ILevelRaycastReceiver.IsValidReceiver(LevelEngine level, HeldItemDefinition definition, IHeldItemData data, PointerEventData d)
        {
            if (Entity.IsPreviewEnemy())
            {
                return true;
            }
            if (definition == null)
                return false;
            var target = GetHeldItemTarget(d);
            var pointer = InputManager.GetPointerDataFromEventData(d);
            return definition.IsValidFor(target, data, pointer);
        }
        int ILevelRaycastReceiver.GetSortingLayer()
        {
            return Model.SortingLayerID;
        }
        int ILevelRaycastReceiver.GetSortingOrder()
        {
            return Model.SortingOrder;
        }
        #endregion

        #region 位置
        private Vector3 GetGroundLocalPosition()
        {
            var pos = Entity.Position;
            var groundY = Entity.GetGroundY();
            var shadowPos = pos;
            shadowPos.y = groundY;

            var worldPosition = Level.LawnToTrans(shadowPos);
            worldPosition.x = transform.position.x;
            worldPosition.z = transform.position.z;
            worldPosition += Level.LawnToTransDistance(modelPropertyCache.ShadowOffset);
            return transform.InverseTransformPoint(worldPosition);
        }
        protected void UpdateShadow()
        {
            var relativeY = Entity.GetRelativeY();
            var scale = Mathf.Max(0, 1 + relativeY / 300) * modelPropertyCache.ShadowScale;

            var alpha = Mathf.Clamp01(1 - relativeY / 300) * modelPropertyCache.ShadowAlpha;

            var hidden = modelPropertyCache.ShadowHidden;

            var shadowTransform = Shadow.transform;
            shadowTransform.localPosition = GetGroundLocalPosition();
            shadowTransform.localScale = scale;
            Shadow.gameObject.SetActive(!hidden);
            Shadow.SetAlpha(alpha);
        }
        private void UpdateHeightIndicator()
        {
            var relativeY = Entity.GetRelativeY();
            bool active = Main.OptionsManager.IsHeightIndicatorEnabled() && Entity.IsVulnerableEntity() && relativeY >= HEIGHT_INDICATOR_MIN_HEIGHT;
            if (heightIndicator.gameObject.activeSelf != active)
            {
                heightIndicator.gameObject.SetActive(active);
            }
            if (active)
            {
                heightIndicator.transform.localPosition = GetGroundLocalPosition();
                heightIndicator.SetHeight(relativeY * Level.LawnToTransScale);
                var t = (relativeY - HEIGHT_INDICATOR_FADE_MIN_HEIGHT) / (HEIGHT_INDICATOR_FADE_MAX_HEIGHT - HEIGHT_INDICATOR_FADE_MIN_HEIGHT);
                var indicatorColor = Color.Lerp(HEIGHT_INDICATOR_COLOR_MIN, HEIGHT_INDICATOR_COLOR_MAX, t);
                heightIndicator.SetColor(indicatorColor);
            }
        }
        protected float GetZOffset()
        {
            float zOffset = 0;
            if (zOffsetDict.TryGetValue(Entity.Type, out float offset))
            {
                zOffset = offset * Level.LawnToTransScale;
            }
            return zOffset;
        }
        protected Vector3 GetTransformOffset()
        {
            float zOffset = GetZOffset();
            return Vector3.back * zOffset;
        }
        #endregion

        #region 护甲
        private void CreateArmorModel(NamespaceID slot, Armor armor)
        {
            if (!Model)
                return;
            if (armor?.Definition == null)
                return;
            var modelID = armor.Definition.GetModelID();
            if (!NamespaceID.IsValid(modelID))
                return;
            var armorID = armor.Definition.GetID();
            var anchor = GetArmorModelAnchor(slot, armorID);
            if (string.IsNullOrEmpty(anchor))
                return;
            var model = Model.CreateArmor(anchor, slot, modelID);
            if (model)
            {
                var modelPosition = GetArmorModelOffset(slot, armorID);
                model.transform.localPosition = modelPosition;
            }
        }
        public Vector3 GetArmorModelOffset(NamespaceID slotID, NamespaceID armorID)
        {
            var shapeDef = Main.Game.GetShapeDefinition(Entity.GetShapeID());
            if (shapeDef != null)
            {
                var offset = shapeDef.GetArmorModelOffset(slotID, armorID);
                offset *= Level.LawnToTransScale;
                return offset;
            }
            return Vector3.zero;
        }
        public string GetArmorModelAnchor(NamespaceID slotID, NamespaceID armorID)
        {
            var game = Main.Game;
            var shapeDef = Main.Game.GetShapeDefinition(Entity.GetShapeID());
            if (shapeDef != null)
            {
                var anchor = shapeDef.GetArmorModelAnchor(slotID, armorID);
                if (!string.IsNullOrEmpty(anchor))
                {
                    return anchor;
                }
            }

            var slotMeta = game.GetArmorSlotDefinition(slotID);
            if (slotMeta != null)
                return slotMeta.Anchor;
            return null;
        }
        private void RemoveArmorModel(NamespaceID slot)
        {
            if (!Model)
                return;
            Model.RemoveArmor(slot);
        }
        private void UpdateArmorModel(NamespaceID slot)
        {
            if (!Model)
                return;
            var armor = Entity.GetArmorAtSlot(slot);
            if (armor == null)
                return;
            var armorModel = Model.GetArmorModel(slot);
            if (!armorModel)
                return;
            var tint = armor.GetTint();
            var colorOffset = armor.GetColorOffset();
            if (slot == VanillaArmorSlots.main)
            {
                tint *= Entity.GetHelmetTint();
                colorOffset += Entity.GetHelmetColorOffset();
            }
            armorModel.GraphicGroup.SetTint(tint);
            armorModel.GraphicGroup.SetColorOffset(colorOffset);
        }
        private void UpdateArmorModels()
        {
            if (!Model)
                return;
            foreach (var slotSlot in Entity.GetActiveArmorSlots())
            {
                UpdateArmorModel(slotSlot);
            }
        }
        public void ClearAllArmorModels()
        {
            var game = Main.Game;
            var slots = game.GetAllArmorSlotDefinitions();
            foreach (var def in slots)
            {
                if (def == null)
                    continue;
                Model.ClearModelAnchor(def.Anchor);
            }
            var shapeDef = Main.Game.GetShapeDefinition(Entity.GetShapeID());
            if (shapeDef != null)
            {
                var anchors = shapeDef.GetAllArmorModelAnchors();
                foreach (var anchor in anchors)
                {
                    Model.ClearModelAnchor(anchor);
                }
            }
        }
        #endregion

        #region 模型
        private void UpdateEntityModel()
        {
            if (!Model)
                return;

            if (Level.IsGameOver() && (Entity.Type == EntityTypes.ENEMY || Entity.Type == EntityTypes.BOSS))
            {
                Model.SetAnimatorInt("State", VanillaEntityStates.WALK);
            }
            var groundPos = Entity.Position;
            groundPos.y = Entity.GetGroundY();
            var transGroundPos = Level.LawnToTrans(groundPos);
            Model.SetGroundY(transGroundPos.y);
            Model.GetCenterTransform().localEulerAngles = Entity.RenderRotation;

            if (modelPropertyCache.IsDirty)
            {
                modelPropertyCache.Update(this);
            }
        }
        private void UpdateModelInsertions()
        {
            Model.UpdateModelInsertions(Entity.GetModelInsertions());
        }
        #endregion

        private void AddCursorSource()
        {
            if (_cursorSource == null)
            {
                _cursorSource = new EntityCursorSource(this, CursorType.Point);
                Main.CursorManager.AddCursorSource(_cursorSource);
            }
        }
        private void RemoveCursorSource()
        {
            if (_cursorSource != null)
            {
                Main.CursorManager.RemoveCursorSource(_cursorSource);
                _cursorSource = null;
            }
        }

        private bool ShouldTwinkle()
        {
            var engine = Entity.Level;
            return engine.ShouldHeldItemMakeEntityTwinkle(Entity);
        }
        private Color GetTint()
        {
            var tint = Entity.GetTint();
            if (twinkling)
            {
                tint *= Level.GetTwinkleColor();
            }
            return tint;
        }
        private Color GetColorOffset()
        {
            var color = Entity.GetColorOffset();
            if (isHighlight)
            {
                color = ColorCalculator.Blend(new Color(1, 1, 1, 0.5f), color, BlendOperator.SrcAlpha, BlendOperator.OneMinusSrcAlpha);
            }
            return color;
        }
        #endregion

        #region View
        public void TriggerView(string name)
        {
            if (Model)
                Model.TriggerAnimator(name);
        }
        public void SetViewBool(string name, bool value)
        {
            if (Model)
                Model.SetAnimatorBool(name, value);
        }
        public void SetViewInt(string name, int value)
        {
            if (Model)
                Model.SetAnimatorInt(name, value);
        }
        public void SetViewFloat(string name, float value)
        {
            if (Model)
                Model.SetAnimatorFloat(name, value);
        }
        #endregion

        #region 事件
        public event Action<EntityController, PointerEventData, PointerInteraction> OnPointerInteraction;
        #endregion

        #region 属性字段
        public const float HEIGHT_INDICATOR_MIN_HEIGHT = 40;
        public const float HEIGHT_INDICATOR_FADE_MIN_HEIGHT = 300;
        public const float HEIGHT_INDICATOR_FADE_MAX_HEIGHT = 500;
        public static readonly Color HEIGHT_INDICATOR_COLOR_MIN = Color.white;
        public static readonly Color HEIGHT_INDICATOR_COLOR_MAX = new Color(1,1,1,0);

        public static readonly Dictionary<int, float> zOffsetDict = new Dictionary<int, float>()
        {
            { EntityTypes.PLANT, 0 },
            { EntityTypes.OBSTACLE, 0 },
            { EntityTypes.BOSS, 2 },
            { EntityTypes.ENEMY, 3 },
            { EntityTypes.PROJECTILE, 4 },
            { EntityTypes.CART, 5 },
            { EntityTypes.EFFECT, 6 },
            { EntityTypes.PICKUP, 7 },
        };
        public MainManager Main => MainManager.Instance;
        public EntityModel Model { get; private set; }
        public ShadowController Shadow => shadow;
        public Entity Entity { get; private set; }
        public LevelController Level { get; private set; }
        private RandomGenerator rng;
        private bool isHighlight;
        private bool twinkling;
        private EntityCursorSource _cursorSource;
        private Vector3 lastPosition;
        private IModelInterface bodyModelInterface;
        private EntityPropertyCache modelPropertyCache = new EntityPropertyCache();
        [SerializeField]
        private ShadowController shadow;
        [SerializeField]
        private HeightIndicatorController heightIndicator;
        [SerializeField]
        private TooltipAnchor tooltipAnchor;
        [SerializeField]
        private LevelPointerInteractionHandler holdStreakHandler;

        ITooltipAnchor ITooltipTarget.Anchor => tooltipAnchor;

        #endregion

        #region 内嵌类

        private class EntityPropertyCache
        {
            public void UpdateAll(EntityController entityCtrl)
            {
                var entity = entityCtrl.Entity;
                var model = entityCtrl.Model;
                var rendererGroup = model.RendererGroup;
                rendererGroup.SetTint(entityCtrl.GetTint());
                rendererGroup.SetHSV(entity.GetHSV());
                rendererGroup.SetColorOffset(entityCtrl.GetColorOffset());
                rendererGroup.SetShaderInt("_Grayscale", entity.IsGrayscale() ? 1 : 0);

                model.transform.localScale = entity.GetFinalDisplayScale();
                model.SortingLayerID = SortingLayer.NameToID(entity.GetSortingLayer());
                model.SortingOrder = entity.GetSortingOrder();
                if (model is EntityModel sprModel)
                {
                    sprModel.SetLightVisible(entity.IsLightSource());
                    sprModel.SetLightColor(entity.GetLightColor());
                    var lightScaleLawn = entity.GetLightRange();
                    var lightScale = new Vector2(lightScaleLawn.x, Mathf.Max(lightScaleLawn.y, lightScaleLawn.z)) * entityCtrl.Level.LawnToTransScale;
                    sprModel.SetLightRange(lightScale);
                }

                ShadowHidden = entity.IsShadowHidden();
                ShadowAlpha = entity.GetShadowAlpha();
                ShadowOffset = entity.GetShadowOffset();
                ShadowScale = entity.GetShadowScale();

                dirtyProperties.Clear();
            }
            public void Update(EntityController entityCtrl)
            {
                var entity = entityCtrl.Entity;
                var model = entityCtrl.Model;
                var rendererGroup = model.RendererGroup;
                foreach (var dirtyProperty in dirtyProperties)
                {
                    switch (dirtyProperty)
                    {
                        case PropertyName.Tint:
                            rendererGroup.SetTint(entityCtrl.GetTint());
                            break;
                        case PropertyName.ColorOffset:
                            rendererGroup.SetColorOffset(entityCtrl.GetColorOffset());
                            break;
                        case PropertyName.HSV:
                            rendererGroup.SetHSV(entity.GetHSV());
                            break;
                        case PropertyName.Grayscale:
                            rendererGroup.SetShaderInt("_Grayscale", entity.IsGrayscale() ? 1 : 0);
                            break;
                        case PropertyName.FlipX:
                        case PropertyName.DisplayScale:
                            model.transform.localScale = entity.GetFinalDisplayScale();
                            break;
                        case PropertyName.SortingLayer:
                            model.SortingLayerID = SortingLayer.NameToID(entity.GetSortingLayer());
                            break;
                        case PropertyName.SortingOrder:
                            model.SortingOrder = entity.GetSortingOrder();
                            break;

                        case PropertyName.ShadowHidden:
                            ShadowHidden = entity.IsShadowHidden();
                            break;
                        case PropertyName.ShadowAlpha:
                            ShadowAlpha = entity.GetShadowAlpha();
                            break;
                        case PropertyName.ShadowOffset:
                            ShadowOffset = entity.GetShadowOffset();
                            break;
                        case PropertyName.ShadowScale:
                            ShadowScale = entity.GetShadowScale();
                            break;

                        case PropertyName.LightSource:
                            {
                                if (model is EntityModel sprModel)
                                {
                                    sprModel.SetLightVisible(entity.IsLightSource());
                                }
                            }
                            break;
                        case PropertyName.LightColor:
                            {
                                if (model is EntityModel sprModel)
                                {
                                    sprModel.SetLightColor(entity.GetLightColor());
                                }
                            }
                            break;
                        case PropertyName.LightRange:
                            {
                                if (model is EntityModel sprModel)
                                {
                                    var lightScaleLawn = entity.GetLightRange();
                                    var lightScale = new Vector2(lightScaleLawn.x, Mathf.Max(lightScaleLawn.y, lightScaleLawn.z)) * entityCtrl.Level.LawnToTransScale;
                                    sprModel.SetLightRange(lightScale);
                                }
                            }
                            break;
                    }
                }
                dirtyProperties.Clear();
            }
            public void SetDirtyProperty(PropertyName property)
            {
                dirtyProperties.Add(property);
            }
            public void SetDirtyProperty(IPropertyKey key)
            {
                foreach (var pair in propertyMap)
                {
                    if (pair.Key.Equals(key))
                    {
                        dirtyProperties.Add(pair.Value);
                        break;
                    }
                }
            }
            public bool IsDirty => dirtyProperties.Count > 0;
            public bool ShadowHidden { get; private set; }
            public Vector3 ShadowOffset { get; private set; }
            public Vector3 ShadowScale { get; private set; }
            public float ShadowAlpha { get; private set; }
            private HashSet<PropertyName> dirtyProperties = new HashSet<PropertyName>();
            private static readonly Dictionary<PropertyMeta, PropertyName> propertyMap = new Dictionary<PropertyMeta, PropertyName>()
            {
                { EngineEntityProps.TINT, PropertyName.Tint },
                { EngineEntityProps.COLOR_OFFSET, PropertyName.ColorOffset },
                { VanillaEntityProps.HSV, PropertyName.HSV },
                { VanillaEntityProps.GRAYSCALE, PropertyName.Grayscale },
                { EngineEntityProps.FLIP_X, PropertyName.FlipX },
                { EngineEntityProps.DISPLAY_SCALE, PropertyName.DisplayScale },
                { VanillaEntityProps.SORTING_LAYER, PropertyName.SortingLayer },
                { VanillaEntityProps.SORTING_ORDER, PropertyName.SortingOrder },

                { VanillaEntityProps.SHADOW_HIDDEN, PropertyName.ShadowHidden },
                { VanillaEntityProps.SHADOW_OFFSET, PropertyName.ShadowOffset },
                { VanillaEntityProps.SHADOW_SCALE, PropertyName.ShadowScale },
                { VanillaEntityProps.SHADOW_ALPHA, PropertyName.ShadowAlpha },

                { VanillaEntityProps.IS_LIGHT_SOURCE, PropertyName.LightSource },
                { VanillaEntityProps.LIGHT_COLOR, PropertyName.LightColor },
                { VanillaEntityProps.LIGHT_RANGE, PropertyName.LightRange },
            };
            public enum PropertyName
            {
                Tint,
                ColorOffset,
                HSV,
                Grayscale,
                FlipX,
                DisplayScale,
                SortingLayer,
                SortingOrder,

                ShadowHidden,
                ShadowOffset,
                ShadowScale,
                ShadowAlpha,

                LightSource,
                LightColor,
                LightRange,
            }
        }
        #endregion
    }
    public class EntityCursorSource : CursorSource
    {
        public EntityCursorSource(EntityController target, CursorType type, int priority = 0)
        {
            this.target = target;
            this.type = type;
            this.priority = priority;
        }

        public override bool IsValid()
        {
            return target && target.isActiveAndEnabled;
        }

        public EntityController target;
        private int priority;
        public override int Priority => priority;
        private CursorType type;
        public override CursorType CursorType => type;
    }
    public class SerializableEntityController
    {
        public long id;
        public SerializableModelData model;
    }
}
